language: node_js
notifications:
  email: false
jobs:
  include:
    - stage: test
      node_js: 6
      script: npm run test
    - node_js: 8
      script: npm run test
    - node_js: 10
      script: npm run test
    - node_js: 12
      script:
        - npm run lint:commit-travis
        - npm run lint
        - npm run test
        - npm run build
    - stage: publish to github
      if: branch = master AND type = push AND fork = false
      node_js: 12
      script: ./scripts/prepare-publish-ci.sh
      before_deploy: ./scripts/prepare-publish-github-ci.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: ./scripts/publish-github-ci.sh
    - stage: publish to npm
      if: tag =~ ^v AND type = push AND fork = false
      node_js: 12
      script: npm run build
      before_deploy: ./scripts/prepare-publish-npm-ci.sh
      deploy:
        on:
          tags: true
        provider: script
        skip_cleanup: true
        script: ./scripts/publish-npm-ci.sh
