
name: Build tarballs for testing
on:
  pull_request:
    branches: [master]

jobs:
  build-tarball:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        package: ['builder', 'eslint-plugin-foreman', 'eslint-plugin-rules', 'find-foreman', 'test', 'vendor-core', 'vendor-dev', 'vendor']

    steps:
    # only run if changes are detected in specified path
    - name: Detect changes
      uses: dorny/paths-filter@v2.2.0
      id: changes
      with:
        filters: |
          matched:
            - packages/${{ matrix.package }}/**
    - name: Set up node
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Checkout foreman-js
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: actions/checkout@v2
    - name: Package tarball
      if: ${{ steps.changes.outputs.matched == 'true' }}
      run:  npm pack
      working-directory: ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: Upload tarball locally
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: 'actions/upload-artifact@v4'
      with:
        name: foreman-js-${{ matrix.package }}-pr-${{ github.event.number }}.tgz
        path: ${{ github.workspace }}/packages/${{ matrix.package }}/theforeman-${{ matrix.package }}-*.tgz
