name: Deploy
on:
  push:
    branches:
      - master
      - 'next**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure foreman-js-bot user
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "foreman-js-bot@theforeman.org"
          git config --global user.name "foreman-js-bot"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          cat ~/.npmrc
          npm whoami
      - name: Install foreman-js npm dependencies
        run: npm install
      - name: Publish to github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/publish-github-ci.sh
      - name: Build foreman-js
        run: npm run build
      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat ~/.npmrc
          npm whoami
          ./scripts/publish-npm-ci.sh
      - name: Comment on the pull-request about the new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/post-publish-comment-github.sh
